name: deploy model

on:
  push:
    branches:
      master
    paths:
    - '**.py'
    - 'requirements.txt'
    - '!get_logs.py'
    - '**.yml'
 
# on:
#   repository_dispatch:
#     types:
#     - model-registered

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install MLflow
      shell: bash
      run: |
        pip install azureml-mlflow

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'code/Iris_pytorch/requirements.txt'
    
    - name: deploy model to ACI
      run: |
       python 'code/Iris_pytorch/deploy_model.py'